import Head from "next/head";

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";

import Image from "next/image";
import logopic from "../public/profile.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";

import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Asif Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="bg-white dark:bg-gray-900 px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developed By Asif</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                {" "}
                <a
                  href="https://mohd-asif.tiiny.site/"
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Asif
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Full Stack Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
              Software Engineer based in India , specializing in technical
              education through hands-on learning and building applications.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3">
            <a target="_blank" href="https://github.com/BeingAsifK">
              <AiFillGithub cursor="pointer" />
            </a>
            <a target="_blank" href="https://linkedin.com/in/BeingAsifK">
              <AiFillLinkedin cursor="pointer" />
            </a>
            <a target="_blank" href="https://twitter.com/BeingAsifK">
              <AiFillTwitterCircle cursor="pointer" />
            </a>
          </div>
          <div className="relative">
            <Image
              className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96"
              src={logopic}
              // layout="fill"
              objectFit="contain"
              alt="profile-pic"
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 text-blue-500">My Projects</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I've embarked on numerous projects throughout the years, but these
              are the ones I hold closest to my heart.So if you come across
              something that piques your interest, feel free to explore the
              codebase and contribute your ideas for further enhancements. Your
              collaboration is highly valued!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://3d-portfolio-asif.netlify.app/">
                <Image
                  src={web1}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://random-code-jokes.netlify.app/">
                <Image
                  src={web3}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://movie-manias.netlify.app/">
                <Image
                  src={web2}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
